const {
  NEXT_PUBLIC_API_PROD_URL,
  NEXT_PUBLIC_API_DEV_URL,

  NEXT_PUBLIC_STRIPE_SECRET,
  NEXT_PUBLIC_API_PROD_URL_STRAPI,
  NEXT_PUBLIC_API_STRAPI_DEV_URL,
  NEXT_PUBLIC_API_STRAPI_DEV_URL_API,

  NODE_ENV
} = process.env;

const PROD = NODE_ENV === "production";

const baseURL = PROD ? NEXT_PUBLIC_API_PROD_URL_STRAPI : NEXT_PUBLIC_API_STRAPI_DEV_URL;

const baseURLSpecial = PROD ? NEXT_PUBLIC_API_PROD_URL_STRAPI : NEXT_PUBLIC_API_STRAPI_DEV_URL_API;

const baseUrlLocation = PROD ? NEXT_PUBLIC_API_PROD_URL : NEXT_PUBLIC_API_DEV_URL;

export {
  PROD,
  baseURL,
  baseURLSpecial,
  baseUrlLocation,
  NEXT_PUBLIC_API_PROD_URL,
  NEXT_PUBLIC_API_DEV_URL,
  NEXT_PUBLIC_STRIPE_SECRET,
  NEXT_PUBLIC_API_PROD_URL_STRAPI,
  NEXT_PUBLIC_API_STRAPI_DEV_URL,
  NEXT_PUBLIC_API_STRAPI_DEV_URL_API
};
